'use strict';
// Manifest-driven evidence reader. Historical round loaders stay frozen.
const fs=require('node:fs'),path=require('node:path'),L=require('./layouts.cjs'),{candidate}=require('./round-four.cjs');
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
function cleanScenario(p){return Object.fromEntries(['id','title','domain','audience','goal','graphShape','split','batch','panelTypes','panelCount','density','graphRole','host','snapshot'].filter(k=>p[k]!==undefined).map(k=>[k,p[k]]));}
function load(round,submission,{complete=false}={}){
 const root=path.resolve(round,'review'),mb=fs.readFileSync(path.join(root,'manifest.json')),manifest=JSON.parse(mb),manifestSha256=L.hash(mb),folder=path.dirname(submission),revisions=[],seen=new Set();
 function read(file){const bytes=fs.readFileSync(file),f=JSON.parse(bytes);if(f.source!=='human-comparison-ui'||f.datasetPurpose!=='human-review'||f.reviewMode!=='panel-layout'||f.evidenceKind!=='explicit-browser-selection')throw Error('Expected genuine explicit panel evidence');if(f.manifestSha256!==manifestSha256||f.datasetId!==manifest.datasetId||f.datasetVersion!==manifest.datasetVersion)throw Error('Feedback manifest identity mismatch');if(!UUID.test(f.submissionId)||!Number.isInteger(f.revision)||f.revision<1)throw Error('Invalid revision identity');const ids=new Set();for(const v of f.choices){const p=manifest.pairs.find(p=>p.id===v.pairId);if(!p||p.split!=='review'||ids.has(v.pairId)||!['A','B','Both','Neither'].includes(v.choice))throw Error('Invalid/duplicate feedback choice');ids.add(v.pairId);for(const label of ['A','B'])for(const k of ['id','sha256','pngSha256'])if(v[label]?.[k]!==p[label]?.[k])throw Error('Feedback candidate identity mismatch');}if(complete&&ids.size!==manifest.pairs.length)throw Error('Incomplete feedback snapshot');return {f,sha256:L.hash(bytes)};}
 const latest=read(submission);let current=latest;
 while(current){const f=current.f;if(seen.has(f.submissionId))throw Error('Revision cycle');seen.add(f.submissionId);revisions.push({submissionId:f.submissionId,revision:f.revision,sha256:current.sha256});if(f.revision===1){if(f.previousSubmissionId)throw Error('Unexpected revision predecessor');break;}if(!UUID.test(f.previousSubmissionId))throw Error('Missing revision predecessor');const previous=read(path.join(folder,'submission-'+f.previousSubmissionId+'.json'));if(previous.f.reviewerId!==f.reviewerId||previous.f.revision!==f.revision-1)throw Error('Revision chain mismatch');current=previous;}
 for(const name of fs.readdirSync(folder).filter(n=>/^submission-.*\.json$/.test(n))){const f=JSON.parse(fs.readFileSync(path.join(folder,name)));if(f.datasetId===latest.f.datasetId&&f.datasetVersion===latest.f.datasetVersion&&f.reviewerId===latest.f.reviewerId&&f.revision>latest.f.revision)throw Error('Newer feedback revision exists');}
 const cases=latest.f.choices.map(v=>{const p=manifest.pairs.find(p=>p.id===v.pairId),specs={A:candidate(root,p,'A'),B:candidate(root,p,'B')};if(L.checkPair(specs.A,specs.B)!==p.contentSha256)throw Error('Frozen source semantic mismatch');const label=['A','B'].includes(v.choice)?v.choice:'A';return {scenario:cleanScenario(p),source:specs[label],sourceCandidate:{label,...p[label]},feedback:{choice:v.choice,reason:v.reason||''},referenceAccepted:v.choice!=='Neither',referenceWinner:['A','B'].includes(v.choice),otherSource:specs[label==='A'?'B':'A']};});
 return {cases,manifest,provenance:{sourceDatasetId:manifest.datasetId,sourceManifestSha256:manifestSha256,feedbackSha256:latest.sha256,feedbackSubmissionId:latest.f.submissionId,feedbackCount:cases.length,revisionChain:revisions,interpretation:'Latest revision replaces earlier choices; Both is acceptance without a winner; Neither is not a positive label; provisional heuristics only'}};
}
module.exports={load,cleanScenario};
