#!/usr/bin/env node
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';
import {execFileSync} from 'node:child_process';
const require=createRequire(import.meta.url);
const {entrypoint,entrypointAssets,fontCss}=require('../source-loader.cjs'),corpus=require('./corpus.cjs'),L=require('./layouts.cjs');
const root=path.resolve(fileURLToPath(new URL('../..',import.meta.url)));
const args=process.argv.slice(2),options={};while(args.length){const k=args.shift();if(!['--output','--seed','--limit'].includes(k)||!args.length)throw Error('Use --output DIR [--seed round-1] [--limit N for smoke captures]');options[k]=args.shift();}
if(!options['--output'])throw Error('--output required');
const out=path.resolve(options['--output']),seed=options['--seed']||'round-1';
try{if((await fs.readdir(out)).length)throw Error('Output is populated; choose a new output directory/version.');}catch(e){if(e.code!=='ENOENT')throw e;}
await fs.mkdir(out,{recursive:true});
// Refuse existing evidence before loading optional browser tooling (also absent in Node-only CI).
const {chromium}=require('../browser-tests/node_modules/@playwright/test');
const C=corpus.engine(),native=entrypoint('native'),assets=entrypointAssets('native'),css=fontCss('all')+'\n'+assets.styles.map(a=>a.source).join('\n');
const harnessCSS='html,body{margin:0;background:#fff}#capture{box-sizing:border-box;padding:20px;background:#fff}.docview{max-width:none;margin:0}.doc-sec{box-shadow:none}*,*::before,*::after{animation:none!important;transition:none!important}';
const html=`<!doctype html><meta charset="utf-8"><style>${css}\n${harnessCSS}</style>${assets.icons}<main id="capture"><div id="view"></div></main><script>${native.body.replace(/<\/script/gi,'<\\/script')}\nwindow.paint=(raw,width,target)=>{if(window.ctl)window.ctl.destroy();document.getElementById('capture').style.width=width+'px';document.getElementById('capture').style.minHeight='';applySkinClasses(document.body,document.getElementById('view'),'pastel');window.ctl=renderPage(document.getElementById('view'),normalize(raw),'pastel',null,{layoutTarget:target});window.ctl.sections[0].stepper.jump(5);};</script>`;
const browser=await chromium.launch({headless:true});console.log('Pinned Chromium '+browser.version());
const context=await browser.newContext({viewport:{width:1600,height:1000},deviceScaleFactor:1,reducedMotion:'reduce',locale:'en-US',timezoneId:'UTC'}),page=await context.newPage(),errors=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
await page.route('**/*',route=>{const u=route.request().url();if(u.startsWith('data:')||u==='about:blank')return route.continue();errors.push('Unexpected resource '+u);return route.abort();});
await page.setContent(html);await page.evaluate(()=>document.fonts.ready);
await page.evaluate(()=>{const OriginalDate=Date;window.Date=class extends OriginalDate{constructor(...args){super(...(args.length?args:['2026-01-15T09:36:00Z']));}static now(){return 1768469760000;}};});
const Viz=require('../../src/workbench/vendor/viz-3.31.0.js'),viz=await Viz.instance(),graphs=new Map();
for(let shape=0;shape<4;shape++){const d=corpus.graph(shape,'context');graphs.set(shape,C.autoArrangeRead(d,viz.renderJSON(C.autoArrangeDot(d,shape===0?'LR':'TB'),{engine:'dot'})));}
const referenceImage=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=640;c.height=360;const x=c.getContext('2d');x.fillStyle='#edf4fb';x.fillRect(0,0,640,360);x.fillStyle='#213c59';x.fillRect(0,0,640,66);x.fillStyle='#fff';x.font='bold 23px "IBM Plex Sans"';x.fillText('FIELD OPERATIONS',24,42);x.fillStyle='#fff';x.fillRect(22,88,596,246);x.fillStyle='#213c59';x.font='20px "IBM Plex Sans"';x.fillText('West site · Observation retained',44,123);x.fillStyle='#17856a';x.fillRect(44,146,14,14);x.fillStyle='#33536c';x.font='17px "IBM Plex Sans"';x.fillText('Gateway online · 09:36 UTC',70,160);for(let i=0;i<3;i++){x.fillStyle=['#cee7f6','#d5eede','#e5def8'][i];x.fillRect(44+i*184,191,164,76);x.fillStyle='#213c59';x.fillText(['EVENT','PROCESS','RECORD'][i],60+i*184,221);x.fillText(['Accepted','186 ms','Stored'][i],60+i*184,249);}x.fillStyle='#63788d';x.fillText('Illustrative screen · fictional data',44,307);return c.toDataURL('image/png');});
const scenarios=corpus.scenarios().slice(0,options['--limit']?Number(options['--limit']):48),corpusBytes=JSON.stringify(scenarios,null,2)+'\n';await fs.writeFile(path.join(out,'corpus.json'),corpusBytes);
const git=args=>{try{return execFileSync('git',['-C',root,...args],{encoding:'utf8'}).trim();}catch{return null;}};
const provenance={version:1,seed,commit:git(['rev-parse','HEAD']),trackedDirty:!!git(['status','--porcelain','--untracked-files=no']),sourceSha256:L.hash(native.body),cssSha256:L.hash(css),harnessSha256:L.hash(html),browserVersion:browser.version(),node:process.version,deviceScaleFactor:1,locale:'en-US',timezone:'UTC',reducedMotion:'reduce',snapshot:5,fixedTime:'2026-01-15T09:36:00Z',graphLayout:'Viz dot via autoArrangeDot/Read/Diagram; frozen before pairing',workbenchSha256:L.hash(entrypoint('workbench').body),vizSha256:L.hash(await fs.readFile(path.join(root,'src/workbench/vendor/viz-3.31.0.js'))),corpusSha256:L.hash(corpusBytes),generatorFiles:{},sources:native.records.map(r=>({file:r.file,sha256:L.hash(r.source)}))};
for(const file of ['corpus.cjs','layouts.cjs','generate.mjs'])provenance.generatorFiles[file]=L.hash(await fs.readFile(new URL(file,import.meta.url)));
const manifest={version:1,reviewMode:'panel-layout',datasetPurpose:'human-review',datasetId:'panel-placement-'+seed,datasetVersion:'v1',title:'Panel arrangements · Round 1',corpusSha256:provenance.corpusSha256,renderer:provenance,pairs:[]},holdouts=[],diagnostics=[];
async function paint(spec,s){await page.evaluate(({spec,s})=>window.paint(spec,s.host.width,s.host.profile),{spec,s});await page.evaluate(async()=>{await document.fonts.ready;await Promise.all(Array.from(document.images).map(i=>i.decode()));await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));});if(errors.length)throw Error(errors.join('\n'));
 const actual=await page.evaluate(()=>Array.from(document.querySelectorAll('.section-layout-tile[data-layout-key^="panel:"]')).map(tile=>{const w=tile.querySelector('.pwidget'),b=w?.querySelector('.pbody');return {key:tile.dataset.layoutKey,text:(w?.textContent||'').replace(/\s+/g,' ').trim(),body:!!b,visible:!!w&&w.getBoundingClientRect().width>0,scroll:w?Math.max(0,w.scrollHeight-w.clientHeight):0,height:w?.scrollHeight||0,horizontal:w?Math.max(0,w.scrollWidth-w.clientWidth):0,nestedScroll:b?Array.from(b.querySelectorAll('*')).filter(e=>e.clientWidth>1&&e.clientHeight>1&&(e.scrollHeight-e.clientHeight>4||e.scrollWidth-e.clientWidth>4)).map(e=>({class:e.className,vertical:e.scrollHeight-e.clientHeight,horizontal:e.scrollWidth-e.clientWidth,overflow:getComputedStyle(e).overflow})):[]};}));
 if(JSON.stringify(actual.map(p=>p.key).sort())!==JSON.stringify(s.panelTypes.map((_,i)=>'panel:p'+i).sort())||actual.length!==s.panelCount||actual.some(x=>!x.body||!x.visible||!x.text.trim()))throw Error('Missing/empty panels '+s.id);return actual;}
try{
 for(const s of scenarios){const source=corpus.specification(C,s,referenceImage);source.page.sections[0].diagram=JSON.parse(JSON.stringify(C.autoArrangeDiagram(L.diagram(source),graphs.get(s.graphShape))));const pair=L.pair(source,s,seed),dest=path.join(out,s.split==='review'?'review':'holdout'),record={...s,A:null,B:null};await fs.mkdir(path.join(dest,'public'),{recursive:true});
  for(const label of ['A','B']){
   const spec=pair[label];let actual;for(let attempt=0;attempt<3;attempt++){const validation=C.validate(C.normalize(spec));if(validation.errors.length||validation.warnings.length)throw Error(s.id+' '+JSON.stringify(validation));actual=await paint(spec,s);const overflow=actual.filter(p=>p.scroll>4);if(!overflow.length)break;for(const p of overflow){const t=L.layout(spec).find(t=>L.key(t)===p.key.replace('panel:','panel:'));t.h=Math.max(t.h,Math.ceil((p.height+8)/40));if(t.h>40)throw Error('Content exceeds40rows '+s.id+' '+p.key);}
   L.diagram(spec).layouts[0].sectionLayout.default=JSON.parse(JSON.stringify(C.sectionLayoutPack(L.layout(spec))));}
   if(actual.some(p=>p.scroll>4||p.horizontal>4))throw Error('Unresolved panel clipping '+s.id+' '+label+' '+JSON.stringify(actual));
   L.check(spec);diagnostics.push({id:s.id,label,panels:actual});
  }
  const last=diagnostics.slice(-2);if(JSON.stringify(last[0].panels.map(p=>[p.key,p.text]).sort())!==JSON.stringify(last[1].panels.map(p=>[p.key,p.text]).sort()))throw Error('Rendered content differs '+s.id+' '+JSON.stringify(last.map(d=>d.panels.map(p=>[p.key,p.text]))));record.contentSha256=L.checkPair(pair.A,pair.B);let canvasHeight=0;for(const label of ['A','B']){await paint(pair[label],s);canvasHeight=Math.max(canvasHeight,Math.ceil(await page.locator('#capture').evaluate(el=>el.getBoundingClientRect().height)));}
  for(const label of ['A','B']){await paint(pair[label],s);await page.locator('#capture').evaluate((el,h)=>el.style.minHeight=h+'px',canvasHeight);const base='public/'+s.id+'-'+label,specBytes=JSON.stringify(pair[label],null,2)+'\n';await fs.writeFile(path.join(dest,base+'.spec.json'),specBytes);let png=await page.locator('#capture').screenshot({animations:'disabled'}),stable=false;for(let attempt=0;attempt<4;attempt++){const repeat=await page.locator('#capture').screenshot({animations:'disabled'});if(L.hash(png)===L.hash(repeat)){stable=true;break;}png=repeat;}if(!stable)throw Error('Unstable screenshot '+s.id+' '+label);await fs.writeFile(path.join(dest,base+'.png'),png);record[label]={id:s.id+'-'+L.hash(specBytes).slice(0,12),sha256:L.hash(specBytes),pngSha256:L.hash(png),spec:base+'.spec.json',png:base+'.png'};}
  record.capture={width:s.host.width,height:canvasHeight,scale:await page.locator('.section-layout-grid').evaluate(el=>Number(getComputedStyle(el).zoom))};if(s.split==='review')manifest.pairs.push(record);else holdouts.push(record);
  console.log('Captured '+s.id+' '+s.panelCount+' panels '+s.host.width+'px');
 }
 await fs.writeFile(path.join(out,'provenance.json'),JSON.stringify(provenance,null,2)+'\n');await fs.writeFile(path.join(out,'capture-report.json'),JSON.stringify({diagnostics,methods:scenarios.map(s=>({id:s.id,...L.pair(corpus.specification(C,s,referenceImage),s,seed).methods})),holdoutCount:holdouts.length},null,2)+'\n');
 await fs.writeFile(path.join(out,'review','manifest.json'),JSON.stringify(manifest,null,2)+'\n');await fs.mkdir(path.join(out,'holdout'),{recursive:true});await fs.writeFile(path.join(out,'holdout','manifest.json'),JSON.stringify({version:1,split:'holdout',pairs:holdouts},null,2)+'\n');
 console.log(JSON.stringify({output:out,review:manifest.pairs.length,holdout:holdouts.length,panelTypes:[...new Set(scenarios.flatMap(s=>s.panelTypes))].sort()}));
}finally{await browser.close();}
