'use strict';
const path=require('node:path'),F=require('./feedback-chain.cjs'),L=require('./layouts.cjs'),R=require('./round-four.cjs');
const FOLLOWUPS=['security-1','hardware-2','api-1','experience-3','distributed-3','overview-3'];
function policy(spec){const rows=L.layout(spec),c=rows.find(t=>t.controls==='steps'),content=rows.filter(t=>!t.controls&&!t.hidden);return c.w<24?'column-band':c.y===0?'above-group':content.every(t=>t.y+t.h<=c.y)?'below-group':'interior-band';}
function depthVariant(item,kind){const source=structuredClone(item.source),d=L.diagram(source);const texts=kind==='short'?['Receive the request.','Validate credentials.','Check the cache.','Call the service.','Persist the result.','Inspect the request trace.']:[
 'Receive the request with its correlation identifier and deadline. Confirm the gateway records the same identifier before forwarding it, so the trace can be compared across the entire request path.',
 'Validate the caller credentials and inspect the authorization result. Distinguish an expired credential from a denied capability; the next action differs even if both appear as a failed request.',
 'Check the cache key, freshness window and backend fallback. Compare the observed response with the stored version, then follow the same correlation identifier into the service. If the cache is stale, preserve the original evidence before retrying; a retry can change the visible symptom. Record which component consumed the latency budget, whether the deadline propagated and whether a fallback response hid an error. These checks separate a cache consistency problem from an overloaded service and keep the recovery decision tied to the actual request.',
 'Call the service and compare its span duration with the remaining deadline. Inspect queue time separately from execution time, and check whether any retry repeats a write that should be idempotent.',
 'Persist the result only after the response has been matched to the request identifier. Verify the durable acknowledgement and inspect the error path before deciding whether the operation can safely be repeated.',
 'Inspect the complete request trace before choosing the next action. Compare gateway, cache and service spans with the end-to-end budget, identify the first unexpected delay, and verify whether the response came from fresh data or fallback. Keep the correlation identifier visible while deciding whether to retry, investigate credentials or examine the service queue. Verify deadline propagation, separate queueing from execution, and check whether a retry could duplicate a write. Preserve the original failure evidence before retrying; a second attempt may change the symptom. Record the first component that diverged from the expected path and explain which observation supports the proposed recovery action.'];d.steps.forEach((s,i)=>s.text=texts[i%texts.length]);return {...item,scenario:{...item.scenario,id:'step-depth-'+kind,title:'Request trace · '+kind+' step narrative',goal:'Compare step-control placement while reading a '+kind+' request-trace explanation.',batch:1},source,axis:'step-depth',freezePacking:true,feedback:null,referenceAccepted:false,referenceWinner:false,syntheticVariation:{kind,displayedSnapshot:5,matchedGroup:'request-trace-depth',sourceCandidateSha256:item.sourceCandidate.sha256,fields:['diagram.steps[].text'],rule:'Same frozen panels, nodes and state; only narrative text changes across this matched pair of experiments',stepTextSha256:L.hash(L.stable(d.steps.map(s=>s.text)))}};}
function load(rounds,feedback,seed){const inputs=rounds.map((r,i)=>F.load(r,feedback[i],{complete:i===3}));for(let i=1;i<4;i++){const renderer=inputs[i].manifest.renderer;if(i===1){if(renderer.feedbackSha256!==inputs[0].provenance.feedbackSha256)throw Error('Feedback chain mismatch');}else for(let j=0;j<i;j++)if(renderer.feedback[j].feedbackSha256!==inputs[j].provenance.feedbackSha256||renderer.feedback[j].sourceManifestSha256!==inputs[j].provenance.sourceManifestSha256)throw Error('Feedback chain mismatch');}
 const followups=FOLLOWUPS.map(id=>{const item=inputs[3].cases.find(c=>c.scenario.id===id);if(!item)throw Error('Missing follow-up');let constraint=null;if(/controls?.*top/i.test(item.feedback.reason))constraint='above-group';if(/B.s step controls/i.test(item.feedback.reason))constraint=policy(item.otherSource);return {...item,axis:'follow-up',freezePacking:id!=='security-1',controlPolicy:constraint};});
 const depth=inputs[3].cases.find(c=>c.scenario.id==='api-1'),experiments=['short','long'].map(kind=>depthVariant(depth,kind));const judged=new Set(inputs.flatMap(i=>i.cases.map(c=>c.scenario.id)));const fresh=R.rankFresh(inputs[0].manifest,judged,followups.map(c=>c.scenario),seed).map(p=>({scenario:F.cleanScenario(p),source:R.candidate(path.join(rounds[0],'review'),p,'A'),sourceCandidate:p.A,axis:'new-case',freezePacking:false,referenceAccepted:false,referenceWinner:false}));return {followups,experiments,fresh,feedback:inputs.map(i=>i.provenance),selectionRule:'Six explicit follow-ups, one matched short/long narrative experiment, four greedily coverage-ranked unjudged public cases; holdouts excluded'};}
module.exports={FOLLOWUPS,load,depthVariant,policy};
