import {test,expect} from '@playwright/test';
import {createRequire} from 'node:module';
import {createCaptureV3} from '../../panel-placement/capture-v3.mjs';
const require=createRequire(import.meta.url),corpus=require('../../panel-placement/corpus.cjs'),L=require('../../panel-placement/layouts.cjs'),S=require('../../panel-placement/solver-v3.cjs'),R=require('../../panel-placement/round-five.cjs');
test('native caption depth probes every step and fits the deepest caption without changing the saved narrative',async()=>{
 const C=corpus.engine(),scenario={...corpus.scenarios().find(s=>s.id==='api-1'),id:'synthetic-depth-browser'},source=corpus.specification(C,scenario,'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aX1kAAAAASUVORK5CYII='),d=L.diagram(source);d.layouts[0].sectionLayout.default=[{x:0,y:0,w:24,h:5,hidden:true},{panel:'p0',x:0,y:0,w:14,h:16},{controls:'steps',x:14,y:0,w:10,h:3}];const item={source,scenario,sourceCandidate:{sha256:'synthetic-source'}},cap=await createCaptureV3();
 try{let shortDepth;for(const kind of ['short','long']){const spec=R.depthVariant(item,kind).source;if(kind==='long')L.diagram(spec).steps[2].text=L.diagram(spec).steps[5].text+' '+L.diagram(spec).steps[5].text;const initial=await cap.paint(spec,scenario),depth=await cap.measureWidths(spec,scenario,initial.geometry);expect(depth[10].states).toHaveLength(6);expect(depth[24].states.map(s=>s.text)).toEqual(L.diagram(spec).steps.map(s=>s.text));if(kind==='short')shortDepth=depth;else{expect(depth[10].neededHeight).toBeGreaterThan(shortDepth[10].neededHeight*2);expect(depth[24].worstStep).toBe(2);expect(initial.narrative.states.some(s=>s.captionClipped>0)).toBeTruthy();}const result=S.solve(spec,{geometry:initial.geometry,freezePacking:true,stepDepth:depth}),observed=await cap.paint(result.spec,scenario);expect(L.semantic(result.spec)).toBe(L.semantic(spec));expect(observed.snapshot.n).toBe(5);for(const n of observed.narrative.states){expect(n.captionClipped).toBe(0);expect(n.buttonsClipped).toBe(0);expect(n.overflowX).toBeLessThanOrEqual(4);expect(n.overflowY).toBeLessThanOrEqual(4);}expect(observed.controls.reachableAfterScroll).toBeTruthy();}}
 finally{await cap.browser.close();}
});
