import {test,expect,paste} from '../helpers/test.mjs';
const spec=()=>({page:{sections:[{heading:'Story',bullets:['First',{text:'Parent',sub:[{text:'Nested point',revealAt:0,custom:true},'Sibling']},'Last'],contract:{fields:[{k:'value',g:'Some context'}],note:'Contract note'},diagram:{nodes:{a:{}},rows:[['a']],steps:[{id:'one',text:'One'},{id:'two',text:'Two'}]}}]}});
test('nested prose supports direct selection, structure changes, formatting and exact Undo',async({page,server},info)=>{
 const original=JSON.stringify(spec(),null,2);await page.goto(server.origin+'/workbench.html');await paste(page,original);
 const root=page.locator('#docview'),guide=page.locator('#guide'),text=guide.locator('.prose-editor textarea');
 const point=address=>root.locator('[data-dv-bullet-path="'+address+'"]');
 await point('1.0').click();await expect(text).toHaveValue('Nested point');
 await text.fill('Updated child');await text.press('Tab');await expect(text).toHaveValue('Updated child');
 let raw=JSON.parse(await page.locator('#src').inputValue());expect(raw.page.sections[0].bullets[1].sub[0]).toEqual({text:'Updated child',revealAt:0,custom:true});
 await guide.getByRole('button',{name:'Move point down',exact:true}).click();await expect(point('1.1')).toHaveClass(/dv-sel/);await expect(text).toHaveValue('Updated child');
 await guide.getByRole('button',{name:'Indent',exact:true}).click();await expect(point('1.0.0')).toHaveClass(/dv-sel/);
 await guide.getByRole('button',{name:'Outdent',exact:true}).click();await expect(point('1.1')).toHaveClass(/dv-sel/);
 await guide.getByRole('button',{name:'Add subpoint',exact:true}).click();await expect(point('1.1.0')).toHaveClass(/dv-sel/);await expect(text).toHaveValue('New subpoint');
 await guide.getByRole('button',{name:'Add sibling',exact:true}).click();await expect(point('1.1.1')).toHaveClass(/dv-sel/);
 await text.focus();await text.selectText();await guide.getByRole('button',{name:'Bold',exact:true}).click();
 await expect(point('1.1.1').locator('strong')).toHaveText('New point');await expect(text).toHaveValue('**New point**');
 await guide.getByLabel('Formatting link URL',{exact:true}).fill('https://example.org/help');
 await text.evaluate(el=>el.setSelectionRange(2,11));await guide.getByRole('button',{name:'Insert link',exact:true}).click();
 await expect(point('1.1.1').locator('a')).toHaveAttribute('href','https://example.org/help');
 await page.screenshot({path:info.outputPath('nested-prose.png')});
 for(let i=0;i<8;i++)await page.locator('#undo-builder').click();await expect(page.locator('#src')).toHaveValue(original);
 await point('1.0').click();await point('1.1').click({modifiers:['Shift']});
 await guide.getByRole('button',{name:'delete 2 bullets',exact:true}).click();
 raw=JSON.parse(await page.locator('#src').inputValue());expect(raw.page.sections[0].bullets[1].sub).toEqual([]);
 await page.locator('#undo-builder').click();await expect(page.locator('#src')).toHaveValue(original);
 await page.locator('#editor-tab-outline').click();await page.locator('#outline-search').fill('Nested point');
 await page.locator('#outline-results button').click();await page.locator('#editor-tab-inspect').click();
 await expect(text).toHaveValue('Nested point');await expect(point('1.0')).toHaveClass(/dv-sel/);
});

test('paragraph formatting keeps the resized textarea height and remains undoable',async({page,server})=>{
 const raw=spec();raw.page.sections[0].text=['Paragraph to format','Another paragraph'];
 const original=JSON.stringify(raw,null,2);
 await page.goto(server.origin+'/workbench.html');await paste(page,original);
 const paragraphs=page.locator('#docview .sec-text');await paragraphs.first().click();
 const guide=page.locator('#guide'),field=guide.getByLabel('Prose text',{exact:true});
 await expect(field).toHaveValue('Paragraph to format');await field.scrollIntoViewIfNeeded();
 const initial=await field.boundingBox();
 await page.mouse.move(initial.x+initial.width-3,initial.y+initial.height-3);
 await page.mouse.down();await page.mouse.move(initial.x+initial.width-3,initial.y+initial.height+117,{steps:12});await page.mouse.up();
 await expect.poll(async()=>(await field.boundingBox()).height).toBeGreaterThan(initial.height+80);
 const resized=(await field.boundingBox()).height;
 await field.focus();await field.selectText();await guide.getByRole('button',{name:'Code block',exact:true}).click();
 await expect(field).toHaveValue(/```[\s\S]*Paragraph to format[\s\S]*```/);
 await expect(paragraphs.first().locator('pre code')).toContainText('Paragraph to format');
 await expect.poll(async()=>(await field.boundingBox()).height).toBe(resized);
 await page.locator('#undo-builder').click();await expect(page.locator('#src')).toHaveValue(original);
 await expect(paragraphs.first().locator('pre')).toHaveCount(0);
 await page.locator('#redo-builder').click();
 await expect(paragraphs.first().locator('pre code')).toContainText('Paragraph to format');
 await paragraphs.nth(1).click();await expect(field).toHaveValue('Another paragraph');
 await expect.poll(async()=>(await field.boundingBox()).height).toBe(initial.height);
});
