import {test,expect,paste} from '../helpers/test.mjs';
const spec=()=>({page:{sections:[{heading:'Story',bullets:['First',{text:'Parent',sub:[{text:'Nested point',revealAt:0,custom:true},'Sibling']},'Last'],contract:{fields:[{k:'value',g:'Some context'}],note:'Contract note'},diagram:{nodes:{a:{}},rows:[['a']],steps:[{id:'one',text:'One'},{id:'two',text:'Two'}]}}]}});
test('nested prose supports direct selection, structure changes, formatting and exact Undo',async({page,server},info)=>{
 const original=JSON.stringify(spec(),null,2);await page.goto(server.origin+'/workbench.html');await paste(page,original);
 const root=page.locator('#docview'),guide=page.locator('#guide'),text=guide.locator('.prose-editor textarea');
 const point=address=>root.locator('[data-dv-bullet-path="'+address+'"]');
 await point('1.0').click();await expect(text).toHaveValue('Nested point');
 await text.fill('Updated child');await text.press('Tab');await expect(text).toHaveValue('Updated child');
 let raw=JSON.parse(await page.locator('#src').inputValue());expect(raw.page.sections[0].bullets[1].sub[0]).toEqual({text:'Updated child',revealAt:0,custom:true});
 await guide.getByRole('button',{name:'Move point down',exact:true}).click();await expect(point('1.1')).toHaveClass(/dv-sel/);await expect(text).toHaveValue('Updated child');
 await guide.getByRole('button',{name:'Indent',exact:true}).click();await expect(point('1.0.0')).toHaveClass(/dv-sel/);
 await guide.getByRole('button',{name:'Outdent',exact:true}).click();await expect(point('1.1')).toHaveClass(/dv-sel/);
 await guide.getByRole('button',{name:'Add subpoint',exact:true}).click();await expect(point('1.1.0')).toHaveClass(/dv-sel/);await expect(text).toHaveValue('New subpoint');
 await guide.getByRole('button',{name:'Add sibling',exact:true}).click();await expect(point('1.1.1')).toHaveClass(/dv-sel/);
 await text.focus();await text.selectText();await guide.getByRole('button',{name:'Bold',exact:true}).click();
 await expect(point('1.1.1').locator('strong')).toHaveText('New point');await expect(text).toHaveValue('**New point**');
 await guide.getByLabel('Formatting link URL',{exact:true}).fill('https://example.org/help');
 await text.evaluate(el=>el.setSelectionRange(2,11));await guide.getByRole('button',{name:'Insert link',exact:true}).click();
 await expect(point('1.1.1').locator('a')).toHaveAttribute('href','https://example.org/help');
 await page.screenshot({path:info.outputPath('nested-prose.png')});
 for(let i=0;i<8;i++)await page.locator('#undo-builder').click();await expect(page.locator('#src')).toHaveValue(original);
 await point('1.0').click();await point('1.1').click({modifiers:['Shift']});
 await guide.getByRole('button',{name:'delete 2 bullets',exact:true}).click();
 raw=JSON.parse(await page.locator('#src').inputValue());expect(raw.page.sections[0].bullets[1].sub).toEqual([]);
 await page.locator('#undo-builder').click();await expect(page.locator('#src')).toHaveValue(original);
 await page.locator('#editor-tab-outline').click();await page.locator('#outline-search').fill('Nested point');
 await page.locator('#outline-results button').click();await page.locator('#editor-tab-inspect').click();
 await expect(text).toHaveValue('Nested point');await expect(point('1.0')).toHaveClass(/dv-sel/);
});
