'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),S=require('../tools/panel-placement/solver-v3.cjs'),L=require('../tools/panel-placement/layouts.cjs'),C=require('../tools/panel-placement/corpus.cjs').engine(),R=require('../tools/panel-placement/round-five.cjs');
function fixture(){return {page:{title:'Abstract report',sections:[{id:'s',diagram:{nodes:{n:{title:'n'}},floats:[{id:'n',x:10,y:10}],steps:[{text:'Check the request.',panels:{}}],panels:[{id:'p',type:'table'}],layouts:[{id:'one',sectionLayout:{columns:24,default:[{x:0,y:0,w:24,h:5},{panel:'p',x:0,y:5,w:14,h:14},{controls:'steps',x:14,y:5,w:10,h:5}]}}]}}]}};}
const geometry={gridWidth:1000,scale:.85,gridTop:340};
function depths(long=false){return Object.fromEntries(Array.from({length:15},(_,i)=>{const w=i+10;return[w,{neededHeight:long?(w<16?680:260):110,maxLines:long?(w<16?26:8):1}];}));}
test('control narrative depth changes width/height selection without repacking evidence',()=>{const source=fixture(),short=S.solve(source,{geometry,freezePacking:true,stepDepth:depths()}),long=S.solve(source,{geometry,freezePacking:true,stepDepth:depths(true)});for(const x of [short,long]){L.check(x.spec);assert.equal(L.semantic(x.spec),L.semantic(source));assert.deepEqual(L.layout(x.spec).filter(t=>!t.controls).map(t=>[t.x,t.w,t.h]),L.layout(source).filter(t=>!t.controls).map(t=>[t.x,t.w,t.h]));}const c=L.layout(long.spec).find(t=>t.controls);assert.equal(c.w,24);assert.ok(c.h>=7);assert.ok(long.metadata.metrics.readingCost>short.metadata.metrics.readingCost);});
test('frozen controls experiments preserve order and source, report y movement, and obey explicit top/interior requests',()=>{const source=fixture(),before=structuredClone(source);for(const controlPolicy of ['above-group','interior-band']){const r=S.solve(source,{geometry,freezePacking:true,stepDepth:depths(),controlPolicy});assert.equal(r.metadata.policy,controlPolicy);assert.ok(r.metadata.verticalMovement.every(x=>Number.isInteger(x.deltaY)));assert.match(r.metadata.selectionRule,/explicit feedback/);L.check(r.spec);}assert.deepEqual(source,before);});
test('generic v3 is invariant to names and metadata order; identical references can be excluded',()=>{const source=fixture(),renamed=structuredClone(source);renamed.page.title='Different';renamed.page.sections[0].id='Other';renamed.page.meta={z:2,a:1};const opts={registry:C.PanelRegistry,geometry,stepDepth:depths()},a=S.solve(source,opts),b=S.solve(renamed,opts);assert.deepEqual(L.layout(a.spec),L.layout(b.spec));assert.deepEqual(S.solve(source,opts),a);const alternate=S.solve(source,{...opts,excludeLayout:L.stable(L.layout(a.spec))});L.checkPair(a.spec,alternate.spec);});
test('matched depth experiments alter only step narrative across cases; within-pair semantics remain exact',()=>{const source=fixture();L.diagram(source).steps=Array.from({length:6},()=>({text:'Original',panels:{}}));const item={source,scenario:{id:'fixture',title:'Original'},sourceCandidate:{sha256:L.hash(L.stable(source))}},short=R.depthVariant(item,'short'),long=R.depthVariant(item,'long');assert.notEqual(L.semantic(short.source),L.semantic(long.source));const scrub=s=>{const c=structuredClone(s);L.diagram(c).steps.forEach(x=>delete x.text);return c;};assert.deepEqual(scrub(short.source),scrub(long.source));assert.deepEqual(scrub(source),scrub(long.source));assert.equal(long.referenceAccepted,false);assert.ok(L.diagram(long.source).steps[5].text.length>L.diagram(long.source).steps[2].text.length);});
test('manifest-driven evidence binds assets and validates latest revision without double-counting',()=>{
 const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),F=require('../tools/panel-placement/feedback-chain.cjs'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'synthetic-step-feedback-'));
 try{fs.mkdirSync(path.join(dir,'review'));fs.mkdirSync(path.join(dir,'synthetic-submissions'));const a=fixture(),b=structuredClone(a);L.layout(b)[1].w=13;const pair={id:'arbitrary-not-a-corpus-id',split:'review',feedbackSha256:'stale',sourceManifestSha256:'stale',contentSha256:L.checkPair(a,b)};for(const [label,spec] of [['A',a],['B',b]]){const bytes=JSON.stringify(spec),png=Buffer.from('synthetic asset');fs.writeFileSync(path.join(dir,'review',label+'.json'),bytes);fs.writeFileSync(path.join(dir,'review',label+'.png'),png);pair[label]={id:label,sha256:L.hash(bytes),pngSha256:L.hash(png),spec:label+'.json',png:label+'.png'};}const manifest={datasetId:'synthetic-unit-test',datasetVersion:'v1',pairs:[pair]},mb=JSON.stringify(manifest);fs.writeFileSync(path.join(dir,'review','manifest.json'),mb);const firstId='00000000-0000-0000-0000-000000000001',secondId='00000000-0000-0000-0000-000000000002',base={source:'human-comparison-ui',datasetPurpose:'human-review',reviewMode:'panel-layout',evidenceKind:'explicit-browser-selection',datasetId:manifest.datasetId,datasetVersion:'v1',manifestSha256:L.hash(mb),reviewerId:'synthetic-test-only',choices:[{pairId:pair.id,choice:'Neither',reason:'Partial preference only',A:pair.A,B:pair.B}]},file=id=>path.join(dir,'synthetic-submissions','submission-'+id+'.json');fs.writeFileSync(file(firstId),JSON.stringify({...base,submissionId:firstId,revision:1}));fs.writeFileSync(file(secondId),JSON.stringify({...base,submissionId:secondId,revision:2,previousSubmissionId:firstId}));const result=F.load(dir,file(secondId),{complete:true});assert.equal(result.cases.length,1);assert.equal(result.provenance.revisionChain.length,2);assert.equal(result.cases[0].referenceWinner,false);assert.equal(result.cases[0].referenceAccepted,false);assert.equal(result.cases[0].scenario.feedbackSha256,undefined);assert.equal(result.cases[0].scenario.sourceManifestSha256,undefined);assert.throws(()=>F.load(dir,file(firstId)),/Newer feedback/);fs.writeFileSync(file(firstId),JSON.stringify({...base,reviewerId:'other',submissionId:firstId,revision:1}));assert.throws(()=>F.load(dir,file(secondId)),/Revision chain/);fs.writeFileSync(file(firstId),JSON.stringify({...base,submissionId:firstId,revision:1}));fs.writeFileSync(path.join(dir,'review','A.png'),'tampered');assert.throws(()=>F.load(dir,file(secondId)),/Source hash mismatch/);
 }finally{fs.rmSync(dir,{recursive:true,force:true});}
});
test('round-five output guard works without browser dependencies or feedback',()=>{const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{spawnSync}=require('node:child_process'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'step-context-guard-'));try{fs.writeFileSync(path.join(dir,'keep'),'unchanged');const args=['tools/panel-placement/generate-round-five.mjs','--output',dir];for(const n of ['one','two','three','four'])args.push('--round-'+n,'missing','--feedback-'+n,'missing');const r=spawnSync(process.execPath,args,{encoding:'utf8'});assert.notEqual(r.status,0);assert.match(r.stderr,/Output is populated/);assert.equal(fs.readFileSync(path.join(dir,'keep'),'utf8'),'unchanged');}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('unconstrained packing does not inherit reference coordinates',()=>{const a=fixture(),b=structuredClone(a),tiles=L.layout(b);Object.assign(tiles[0],{x:0,y:0,w:12,h:10});Object.assign(tiles[1],{x:12,y:0,w:12,h:18});Object.assign(tiles[2],{x:0,y:18,w:24,h:4});L.check(b);const options={registry:C.PanelRegistry,geometry,stepDepth:depths()};assert.deepEqual(L.layout(S.solve(a,options).spec),L.layout(S.solve(b,options).spec));});
