'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const corpus=require('../tools/panel-placement/corpus.cjs'),L=require('../tools/panel-placement/layouts.cjs'),A=require('../tools/panel-placement/adaptive.cjs'),F=require('../tools/panel-placement/feedback.cjs');
const C=corpus.engine(),image='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aX1kAAAAASUVORK5CYII=';
function source(s){const spec=corpus.specification(C,s,image),d=L.diagram(spec);d.floats=Object.keys(d.nodes).map((id,i)=>({id,x:120+(i%2)*200,y:100+Math.floor(i/2)*100,side:'below'}));d.rows=[[]];return L.pair(spec,s,'fixture').A;}
test('compact status priors respond to actual row count and detailed content',()=>{
 const small=A.prior({type:'checks',checks:[{id:'one'}]}),dense=A.prior({type:'checks',checks:Array.from({length:12},(_,i)=>({id:String(i)}))});assert.ok(small.w<=5&&small.h===3);assert.ok(dense.w>small.w&&dense.h>small.h);
 const state=A.prior({type:'state',initial:{state:'Ready'}}),verbose=A.prior({type:'state',initial:{state:'Detailed observation '.repeat(180)}});assert.ok(verbose.w>state.w&&verbose.h>state.h);assert.ok(A.prior({type:'screen'}).w<12);
});
test('focused pairs isolate sizing or controls, preserve frozen identity and keep controls ahead of long reports',()=>{
 const all=corpus.scenarios(),ids=[...A.SIZING,...A.CONTROLS];assert.equal(ids.length,12);assert.equal(A.SIZING.size,6);assert.equal(A.CONTROLS.size,6);
 for(const id of ids){const s=all.find(s=>s.id===id),original=source(s),before=JSON.stringify(original),pair=A.pair(original,s);assert.equal(JSON.stringify(original),before);assert.deepEqual(A.pair(original,s),pair);
  for(const label of ['A','B']){const c=pair[label];L.check(c.spec);assert.equal(L.semantic(c.spec),L.semantic(original));assert.deepEqual(L.diagram(c.spec).floats,L.diagram(original).floats);assert.deepEqual(JSON.parse(JSON.stringify(C.validate(C.normalize(c.spec)))),{errors:[],warnings:[]});const controls=L.layout(c.spec).find(t=>t.controls);assert.equal(controls.w,24);assert.ok(!controls.attachTo&&!controls.hidden);for(const pid of c.metadata.secondaryIds)assert.ok(L.layout(c.spec).find(t=>t.panel===pid).y>=controls.y+controls.h);}
  const dimensions=c=>L.layout(c.spec).filter(t=>t.panel).map(t=>[t.panel,t.w,t.h]);if(A.CONTROLS.has(id)){assert.deepEqual(dimensions(pair.A),dimensions(pair.B));assert.notEqual(pair.A.metadata.policy,pair.B.metadata.policy);}else{assert.equal(pair.A.metadata.policy,pair.B.metadata.policy);assert.notDeepEqual(dimensions(pair.A),dimensions(pair.B));}
 }
});
test('narrow graph group stacks warehouse and hardware panels and places controls under the whole group',()=>{
 for(const id of ['warehouse-1','hardware-2']){const s=corpus.scenarios().find(s=>s.id===id),original=source(s),d=L.diagram(original);d.floats.forEach((p,i)=>{p.x=150+(i%2)*100;p.y=100+Math.floor(i/2)*120;});const candidate=A.build(original,s,'compact','under-primary'),tiles=L.layout(candidate.spec),graph=tiles.find(t=>!t.panel&&!t.controls),controls=tiles.find(t=>t.controls),panels=tiles.filter(t=>t.panel);assert.equal(candidate.metadata.graph.narrow,true);assert.ok(graph.w<24);assert.equal(new Set(panels.map(t=>t.x)).size,1);assert.ok(panels.every(t=>t.x===graph.w));assert.ok(tiles.filter(t=>!t.controls&&!t.hidden).every(t=>t.y+t.h<=controls.y));}
});
test('diagnostic penalty penalizes inaccessible controls, clipped content and unreadable nodes',()=>{
 const s=corpus.scenarios()[0],spec=source(s),o={panels:[{emptyAreaFraction:.1,overflowX:0,overflowY:0}],controls:{bottom:700},graph:{clippedNodes:0,minimumLabelPx:10}};const baseline=A.score(spec,o).penalty;for(const change of [v=>v.controls.bottom=1100,v=>v.panels[0].overflowY=50,v=>v.graph.clippedNodes=1,v=>v.graph.minimumLabelPx=5,v=>v.controls.overflowY=12,v=>v.controls.reachableAfterScroll=false]){const changed=structuredClone(o);change(changed);assert.ok(A.score(spec,changed).penalty>baseline);}
});
test('feedback loader binds explicit source identity and refuses tampered snapshots',()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'synthetic-focused-evidence-'));try{const review=path.join(dir,'review');fs.mkdirSync(path.join(review,'public'),{recursive:true});const manifest={datasetId:'synthetic-evidence',datasetVersion:'v1',pairs:[]},choices=[];
  for(const id of [...A.SIZING,...A.CONTROLS]){const scenario=corpus.scenarios().find(s=>s.id===id),a=source(scenario),pair=A.pair(a,scenario),row={...scenario,contentSha256:L.checkPair(pair.A.spec,pair.B.spec)};for(const label of ['A','B']){const bytes=JSON.stringify(pair[label].spec),base='public/'+id+'-'+label;fs.writeFileSync(path.join(review,base+'.json'),bytes);fs.writeFileSync(path.join(review,base+'.png'),'synthetic pixels');row[label]={id:id+'-'+label,sha256:L.hash(bytes),pngSha256:L.hash('synthetic pixels'),spec:base+'.json',png:base+'.png'};}manifest.pairs.push(row);choices.push({pairId:id,choice:'Neither',...Object.fromEntries(['A','B'].map(label=>[label,Object.fromEntries(['id','sha256','pngSha256'].map(k=>[k,row[label][k]]))]))});}
  const bytes=JSON.stringify(manifest);fs.writeFileSync(path.join(review,'manifest.json'),bytes);const submission=path.join(dir,'synthetic-feedback.json'),feedback={source:'human-comparison-ui',datasetPurpose:'human-review',reviewMode:'panel-layout',datasetId:manifest.datasetId,datasetVersion:'v1',manifestSha256:L.hash(bytes),choices};fs.writeFileSync(submission,JSON.stringify(feedback));assert.equal(F.load(dir,submission).cases.length,12);fs.appendFileSync(path.join(review,manifest.pairs[0].A.spec),' ');assert.throws(()=>F.load(dir,submission),/hash mismatch/);
 }finally{fs.rmSync(dir,{recursive:true,force:true});}
});

test('focused generator refuses populated output before browser or feedback loading',()=>{const {spawnSync}=require('node:child_process'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'synthetic-round-two-guard-'));try{fs.writeFileSync(path.join(dir,'evidence'),'preserved');const result=spawnSync(process.execPath,[path.resolve(__dirname,'../tools/panel-placement/generate-round-two.mjs'),'--round-one','missing-source','--feedback','missing-feedback','--output',dir],{encoding:'utf8'});assert.notEqual(result.status,0);assert.match(result.stderr,/Output is populated/);assert.equal(fs.readFileSync(path.join(dir,'evidence'),'utf8'),'preserved');}finally{fs.rmSync(dir,{recursive:true,force:true});}});
