'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const corpus=require('../tools/panel-placement/corpus.cjs'),L=require('../tools/panel-placement/layouts.cjs');
const C=corpus.engine(),image='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aX1kAAAAASUVORK5CYII=';
test('48 distinct fictional scenarios cover32 types,1–8 panels and a sealed12-scenario split',()=>{const all=corpus.scenarios();assert.equal(all.length,48);assert.equal(new Set(all.map(s=>s.id)).size,48);assert.deepEqual(corpus.scenarios(),all);assert.equal(new Set(all.flatMap(s=>s.panelTypes)).size,32);assert.deepEqual([...new Set(all.map(s=>s.panelCount))].sort(),[1,2,3,4,5,6,7,8]);const review=all.filter(s=>s.split==='review');assert.equal(review.length,36);assert.equal(all.filter(s=>s.split==='holdout').length,12);for(let batch=1;batch<=3;batch++){const rows=review.filter(s=>s.batch===batch);assert.equal(rows.length,12);for(const variant of ['1','2','3'])assert.equal(rows.filter(s=>s.id.endsWith('-'+variant)).length,4);for(const role of ['hidden','diagram-dominant','panel-dominant'])assert.equal(rows.filter(s=>s.graphRole===role).length,4);for(const width of [800,1000,1440])assert.equal(rows.filter(s=>s.host.width===width).length,4);}});
test('every pair has real valid panel content, meaningful independent geometry and exact immutable semantics',()=>{for(const s of corpus.scenarios()){const source=corpus.specification(C,s,image),before=JSON.stringify(source),p=L.pair(source,s,'round-1');assert.equal(JSON.stringify(source),before);assert.deepEqual(L.pair(source,s,'round-1'),p);assert.equal(L.checkPair(p.A,p.B),L.hash(L.semantic(p.A)));for(const spec of [p.A,p.B]){const v=C.validate(C.normalize(spec));assert.deepEqual(JSON.parse(JSON.stringify(v)),{errors:[],warnings:[]},s.id);assert.ok(L.layout(spec).some(t=>t.controls==='steps'));assert.equal(L.diagram(spec).panels.length,s.panelCount);assert.ok(L.diagram(spec).panels.every(p=>p.title&&Object.keys(p).length>3));}const deltas=L.layout(p.A).map((t,i)=>Math.abs(t.x-L.layout(p.B)[i].x)+Math.abs(t.y-L.layout(p.B)[i].y)+Math.abs(t.w-L.layout(p.B)[i].w)+Math.abs(t.h-L.layout(p.B)[i].h));assert.ok(deltas.some(d=>d>=4),s.id+' has a meaningful alternative');}});
test('content, visibility, state, order and malformed bounds cannot masquerade as placement changes',()=>{const s=corpus.scenarios()[0],p=L.pair(corpus.specification(C,s,image),s,'round-1');for(const mutate of [s=>L.diagram(s).panels[0].title='changed',s=>L.diagram(s).steps[0].text='changed',s=>L.layout(s)[0].hidden=true,s=>L.diagram(s).edges.reverse(),s=>L.layout(s)[0].w=25,s=>L.layout(s)[0].x=.5,s=>L.diagram(s).layouts[0].sectionLayout.columns=12]){const b=corpus.clone(p.B);mutate(b);assert.throws(()=>L.checkPair(p.A,b));}assert.throws(()=>L.checkPair(p.A,p.A),/Identical/);});

test('generation refuses a populated output before replacing evidence',()=>{const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{spawnSync}=require('node:child_process');const dir=fs.mkdtempSync(path.join(os.tmpdir(),'synthetic-round-no-overwrite-'));try{fs.writeFileSync(path.join(dir,'evidence'),'preserved');const preload=path.join(dir,'no-browser.cjs');fs.writeFileSync(preload,"const Module=require('node:module'),load=Module._load;Module._load=function(id,...args){if(id.includes('@playwright/test'))throw Error('Browser dependency must not load before output validation');return load.call(this,id,...args);};");const result=spawnSync(process.execPath,['--require',preload,path.resolve(__dirname,'../tools/panel-placement/generate.mjs'),'--output',dir],{encoding:'utf8'});assert.notEqual(result.status,0);assert.match(result.stderr,/Output is populated/);assert.equal(fs.readFileSync(path.join(dir,'evidence'),'utf8'),'preserved');}finally{fs.rmSync(dir,{recursive:true,force:true});}});
