/* Pure import/export preparation. Browser resources and publication live in io.js. */

/* ---------------- Mermaid sequence skeleton ---------------- */

function mermaidToSpec(text){
  if (typeof text !== 'string') throw new Error('line 1: expected mermaid text');
  /* Match the CLI: the first mermaid fence wins, even if it is not a sequence. */
  var fence = /^```mermaid\s*$([\s\S]*?)^```\s*$/m.exec(text);
  var lines = (fence ? fence[1] : text).split(/\r\n|[\n\r\v\f\x1c-\x1e\x85\u2028\u2029]/)
    .map(function(ln){ return ln.trim(); }).filter(function(ln){ return ln; });
  if (!lines.length || lines[0] !== 'sequenceDiagram')
    throw new Error('line 1: not a sequenceDiagram (first line is ' +
      JSON.stringify(lines[0] || '<empty>') + '); only mermaid sequenceDiagram input is supported');
  var order = [], titles = Object.create(null), messages = [], todos = [];
  var depth = 0, skipped = 0, header = null, blockLine = 0, n = 1;
  function ensure(pid, title){
    var id = pid.toLowerCase().replace(/[^a-z0-9]+/g, '');
    if (!id) throw new Error('line ' + n + ': participant id ' + JSON.stringify(pid) + ' slugs to nothing');
    if (!Object.prototype.hasOwnProperty.call(titles, id)){
      order.push(id);
      titles[id] = title || pid;
    } else if (title) titles[id] = title;
    return id;
  }
  for (var i = 1; i < lines.length; i++){
    var ln = lines[i];
    n = i + 1; /* CLI line numbers count nonblank lines. */
    if (ln === 'autonumber') continue;
    if (/^Note\b/i.test(ln)){
      todos.push('note not converted: ' + ln);
      continue;
    }
    var b = /^(alt|opt|loop|par)\b\s*(.*)$/.exec(ln);
    if (b){
      if (!depth){ header = (b[1] + ' ' + b[2]).trim(); skipped = 0; blockLine = n; }
      depth++;
      continue;
    }
    if (ln === 'else' || ln.indexOf('else ') === 0){
      if (!depth) throw new Error('line ' + n + ": 'else' outside a block");
      continue;
    }
    if (ln === 'end'){
      if (!depth) throw new Error('line ' + n + ": 'end' without an open block");
      depth--;
      if (!depth) todos.push(header + ' block not converted (' + skipped + ' message(s) inside) — add by hand');
      continue;
    }
    var p = /^participant\s+(\S+?)(?:\s+as\s+(.+?))?\s*$/.exec(ln);
    if (p){
      if (!depth) ensure(p[1], p[2]);
      continue;
    }
    var m = /^(\S+?)\s*(-->>|->>)\s*(\S+?)\s*:\s*(.+?)\s*$/.exec(ln);
    if (m){
      if (depth){ skipped++; continue; }
      messages.push({from: ensure(m[1]), to: ensure(m[3]), ret: m[2] === '-->>', text: m[4]});
      continue;
    }
    throw new Error('line ' + n + ': unsupported syntax ' + JSON.stringify(ln) +
      ' — supported: participant, ->> / -->> messages, autonumber, alt/opt/loop/par blocks, Note');
  }
  if (depth) throw new Error('line ' + blockLine + ': unclosed alt/opt/loop/par block');
  if (!messages.length) throw new Error('line ' + n + ': no messages found outside alt/opt/loop/par blocks');
  var edges = [], pairs = Object.create(null), steps = [];
  messages.forEach(function(m){
    var key = m.from + '->' + m.to;
    if (!pairs[key]){
      var kind = /https?|POST|GET/i.test(m.text) ? 'https' :
        /publish|subscribe|mqtt|qos/i.test(m.text) ? 'mqtt' : 'int';
      var edge = {from: m.from, to: m.to, kind: kind, label: m.text};
      if (m.ret) edge.ret = true;
      pairs[key] = true;
      edges.push(edge);
    }
    steps.push({edge: key, text: m.text});
  });
  var half = Math.floor((order.length + 1) / 2), rows = [order.slice(0, half)], nodes = {};
  if (order.length > half) rows.push(order.slice(half));
  order.forEach(function(id){ nodes[id] = {title: titles[id], sub: '', icon: 'gear', tint: 'cmd'}; });
  var title = 'Converted sequence';
  return {page: {title: title, sections: [{heading: title,
    text: ['Skeleton generated by mermaid2spec.py — enrich titles, subs, icons, tints, protocols, and prose before use.'],
    diagram: {view: 'ambient', nodes: nodes, rows: rows, edges: edges, steps: steps}
  }]}, todos: todos};
}

/* ---------------- durability: filenames ---------------- */

function specFileName(raw){
  /* download name for the save button: page-title slug + .spec.json */
  var page = raw && raw.page ? raw.page : raw;
  var title = page && typeof page.title === 'string' ? page.title : '';
  var slug = title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
  return (slug || 'flowspec') + '.spec.json';
}

/* ---------------- export: spec -> published page ----------------
   Client-side mirror of tools/inject.py: swap the template's one
   line-anchored flowspec JSON block for the editor text and retitle
   the page. Tag literals are concatenated so this file survives being
   inlined into a <script> block by the build. */

var FLOWSPEC_OPEN = '<scr' + 'ipt type="application/json" id="flowspec">';

var FLOWSPEC_CLOSE = '</scr' + 'ipt>';

function exportTemplateOpeners(templateText){
  /* line-anchored flowspec block openers (optional CR before the line
     end so CRLF templates count too) */
  var openRe = new RegExp('^' + FLOWSPEC_OPEN.replace(/[/\\^$.*+?()[\]{}|]/g, '\\$&') + '\\r?$', 'gm');
  return (templateText.match(openRe) || []).length;
}

function buildExportHtml(templateText, specText){
  /* the close-tag scan is case-insensitive — HTML tag names are, so
     "</SCRIPT" would break out of the JSON block just as surely */
  if (/<\/script/i.test(specText))
    return {error: 'the spec contains a literal "</scr' + 'ipt" — escape it as "<\\/scr' + 'ipt" first'};
  var spec;
  try { spec = JSON.parse(specText); }
  catch (ex){ return {error: 'not valid JSON (' + ex.message + ')'}; }
  var openRe = new RegExp('^' + FLOWSPEC_OPEN.replace(/[/\\^$.*+?()[\]{}|]/g, '\\$&') + '\\r?$', 'gm');
  var opens = templateText.match(openRe) || [];
  if (opens.length !== 1)
    return {error: 'the page template must hold exactly one flowspec block — found ' + opens.length};
  var start = templateText.search(openRe);
  var bodyFrom = start + FLOWSPEC_OPEN.length;
  var end = templateText.indexOf('\n' + FLOWSPEC_CLOSE, bodyFrom);
  if (end < 0) return {error: 'the page template’s flowspec block never closes'};
  var out = templateText.slice(0, bodyFrom) + '\n' + specText.trim() +
            templateText.slice(end);
  var page = spec && spec.page ? spec.page : spec;
  var title = page && typeof page.title === 'string' ? page.title : '';
  if (title){
    var safe = title.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
    out = out.replace(/<title>[\s\S]*?<\/title>/, '<title>' + safe + '</title>');
  }
  return {html: out};
}
