/* Build-time artifacts compiled into source-free distributions.
   Authored sources, declarations and license inputs remain in src/. */
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {transform} from 'esbuild';
import sourceLoader from '../../tools/source-loader.cjs';
import {nativeViewerSource} from '../../tools/native-viewer-build.mjs';
const app=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(app,'../..');
const read=name=>readFile(path.join(root,name),'utf8');
const js=(await transform(await nativeViewerSource(), {minify:true,target:'es2020',format:'esm',legalComments:'none'})).code;
const licenses=sourceLoader.entrypointAssets('native').licenses.map(license=>license.text);
const outputs={
  'nativeViewer.js':'// Generated by apps/backstage/build-viewer.mjs; trusted package code/assets, never diagram data.\n'+js,
  'nativeViewer.d.ts':await read('src/native/mount.d.ts'),
  'FONT-LICENSES.txt':licenses.join('\n\n'),
  'compatibility.js':'// Generated by apps/backstage/build-viewer.mjs.\n'+sourceLoader.moduleSource('compatibility'),
  'compatibility.d.ts':await read('src/compatibility.d.ts'),
};
const out=path.join(app,'src/generated');await mkdir(out,{recursive:true});
for(const [name,content] of Object.entries(outputs)) await writeFile(path.join(out,name),content);
console.log('Backstage native viewer built ('+Buffer.byteLength(js)+' bytes; embedded assets)');
