/* Portable committed artifact: a company workspace can copy this plugin without
   the design-viz checkout. Regenerate here whenever shared viewer inputs change. */
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {transform} from 'esbuild';
import sourceLoader from '../../tools/source-loader.cjs';
const app=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(app,'../..');
const read=name=>name.startsWith('src/') && name.endsWith('.js') ? sourceLoader.readSource(name.slice(4)) :
  name==='src/style.core.css' ? sourceLoader.readStyles('style.core.css') : readFile(path.join(root,name),'utf8');
const sources=['src/compatibility.js','src/canon.js','src/validator.js','src/engine.js','apps/backstage/viewer/frame.js'];
const js=(await transform('(function(){\n'+(await Promise.all(sources.map(read))).join('\n')+'\n})();', {minify:true,target:'es2020',legalComments:'none'})).code;
const hash=createHash('sha256').update(js).digest('base64');
const policy="default-src 'none'; script-src 'sha256-"+hash+"'; style-src 'unsafe-inline'; font-src data:; img-src data:; connect-src 'none'; frame-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none'; worker-src 'none'";
let fonts='';
for(const font of JSON.parse(await read('src/fonts/manifest.json'))){
  const data=await readFile(path.join(root,'src/fonts',font.file));
  fonts+=`@font-face{font-family:'${font.family}';font-style:normal;font-weight:${font.weight};font-display:swap;src:url(data:font/woff2;base64,${data.toString('base64')}) format('woff2');}\n`;
}
const licenses=await Promise.all(['ibm-plex-sans','ibm-plex-mono','sora','newsreader','source-sans-3','plus-jakarta-sans','barlow-condensed'].map(pkg=>read('src/fonts/'+pkg+'-LICENSE.txt')));
const licenseText=licenses.join('\n\n');
const css='/* Bundled font licenses\n'+licenseText.replaceAll('*/','* /')+'\n*/\n'+fonts+(await Promise.all(['src/style.flowview.css','src/style.core.css','apps/backstage/viewer/frame.css'].map(read))).join('\n');
const html='<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="'+policy+'"><meta name="referrer" content="no-referrer"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Flowview diagram</title><style>'+css+'</style></head><body>'+await read('src/icons.svg')+'<div id="viewer-error" role="alert" hidden></div><div id="docview" class="docview"></div><script>'+js+'</script></body></html>';
const out=path.join(app,'src/generated');await mkdir(out,{recursive:true});
const output='// Generated by apps/backstage/build-viewer.mjs; contains trusted code/assets, never diagram data.\nexport const viewerDocument = '+JSON.stringify(html)+';\nexport const viewerScriptCsp = '+JSON.stringify("'sha256-"+hash+"'")+';\n';
const compatibility='// Generated by apps/backstage/build-viewer.mjs.\n'+await read('src/compatibility.js')+'\nexport {FlowviewCompatibility};\n';
const compatibilityTypes=await read('src/compatibility.d.ts');
if(process.argv.includes('--check')){
  if(await readFile(path.join(out,'viewerDocument.ts'),'utf8')!==output)throw new Error('Bundled Backstage viewer is stale. Run npm run build:viewer in apps/backstage.');
  if(await readFile(path.join(out,'FONT-LICENSES.txt'),'utf8')!==licenseText)throw new Error('Bundled font licenses are stale. Run npm run build:viewer.');
  if(await readFile(path.join(out,'compatibility.js'),'utf8')!==compatibility || await readFile(path.join(out,'compatibility.d.ts'),'utf8')!==compatibilityTypes)
    throw new Error('Bundled compatibility checker is stale. Run npm run build:viewer.');
}else{
  await writeFile(path.join(out,'viewerDocument.ts'),output);
  await writeFile(path.join(out,'FONT-LICENSES.txt'),licenseText);
  await writeFile(path.join(out,'compatibility.js'),compatibility);
  await writeFile(path.join(out,'compatibility.d.ts'),compatibilityTypes);
}
console.log('Backstage viewer '+(process.argv.includes('--check')?'is fresh':'built')+' ('+Buffer.byteLength(html)+' bytes; no network resources)');
